---
version: '3.7'

services:
  backend:
    build: ./foundry-backend
    ports:
      - 30000:30000
    volumes:
      - /home/kroot/foundryuserdata:/home/foundryvtt/foundryuserdata

  proxy:
    image: kryssperer/foundry_nginx
    ports:
     - 30080:80
