---
version: '3.7'

services:
  backend:
    build: ./foundry-backend
#    ports: 
#      - 30000:30000
    volumes: 
      - <PATH TO YOUR FOUNDRY DATA>:/home/foundryvtt/foundryuserdata

  proxy: 
    build: ./proxy
    ports: 
     - 80:80